### PR TITLE
Parallel loop for COVAREP feature and formant extraction

### PR DESCRIPTION
**Pull request by codacola**
COVAREP_parallel: Parallel for-loop like the one in @schererstefan 's COVAREP_formant_extraction wrapping @twoertwein 's COVAREP_feature_formant_extraction.

### CODE REVIEW

**Comment by twoertwein** [comment]
two minor things (not sure whether that is important):
- if someone calls this function with the option `gender`, this gender will be used for all audio files. 
- same for `save_mat `and `save_csv`. If they are strings, it will override the files. If they are booleans, everything is fine (`COVAREP_formant_extraction` then determines the file based on the audio file)

**Comment by codacola** [comment]
> same for save_matand save_csv. If they are strings, it will override the files. If they are booleans, everything is fine (COVAREP_formant_extraction then determines the file based on the audio file)
True, shall I we include a check and throw an error there ?

>if someone calls this function with the option gender, this gender will be used for all audio files.
For me one option per folder (incl. gender) was sufficient, but something more versatile would be nice. Like one option file per wav (e.g. subject1.wav  and subject1.opt) what do you think ?

**Comment by twoertwein** [comment]
I personally do not have a strong opinion about it, since I usually call the function file-by-file. I would assume that people who want to have the convenience of not having to write a for loop themselves, would not make the effort to specify any options

**Comment by gillesdegottex** [comment]
Hi guys, thanks for the contribution!
I think it is necessary to make these function names a bit more consistent with the previous ones.
Rename:
COVAREP_feature_formant_extraction.m -> COVAREP_feature_formant_extraction_perfile.m
COVAREP_parallel_feature_formant_extraction -> COVAREP_feature_formant_extraction.m

Regarding the two points mentioned by @twoertwein twoertwein, I think the best is to follow the same approach used in the original COVAREP_feature_extraction.m

@codacola do you have a bit of time to make us a pull request with the necessary changes?

**Comment by gillesdegottex** [comment]
All good for you @twoertwein ?

**Comment by twoertwein** [comment]
yes :+1:

**Comment by BrankaZei** [comment]
Hello,

Please tell me how to unsubscribe

Kind regards

Branka

-----------------------------------------

Branka Zei Pollermann PhD

Director

Vox Institute

Address: 17 rue des Maraîchers, 1205 Genève

tel: +41 (0)22 328 76 74

mobile: +41(0)79 203 92 17

 

http://www.vox-institute.ch/

**Pull request merged**
